version: "3.7"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.1.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  kafka:
    image: confluentinc/cp-kafka:6.1.0
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    ports:
      - "9092:9092"
      - "9094:9094"
    depends_on:
      - zookeeper
  redis:
    image: redis:6.2.1-alpine
    ports:
      - "6379:6379"
  flink:
    image: 1034552569/pyflink:v0.5
    container_name: flink
    entrypoint: ["bash", "-c", "sleep 9999999999999"]
    volumes:
      - ./hiveconf:/opt/hive/conf
      - ./flinklib:/opt/flink/lib
      - ../pyflink:/flink

# hive containers begin
# 参考了视频：https://www.youtube.com/watch?v=jLjdjWaKrl0
# 和两个项目： 1. https://github.com/big-data-europe/docker-hive，它提供了 2.3.2 版
# 本的 hive。
# 2. https://github.com/big-data-europe/docker-hadoop-spark-workbench，是 spack 的 docker 开发环境，内部使用了 hive 2.1.0。
# 修改 1 中 namenode,datanode,hive-server,hive-metastore,hive-metastore-postgresql 的镜像版本为 2 得到的。
  namenode:
    image: bde2020/hadoop-namenode:1.1.0-hadoop2.8-java8
    volumes:
      - namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop-hive.env
    ports:
      - "50070:50070"
  datanode:
    image: bde2020/hadoop-datanode:1.1.0-hadoop2.8-java8
    volumes:
      - datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop-hive.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    ports:
      - "50075:50075"
  hive-server:
    image: bde2020/hive:2.1.0-postgresql-metastore
    container_name: hive-server
    env_file:
      - ./hadoop-hive.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    ports:
      - "10000:10000"
    volumes:
      - ./hiveconf:/opt/hive/conf
  hive-metastore:
    image: bde2020/hive:2.1.0-postgresql-metastore
    env_file:
      - ./hadoop-hive.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 hive-metastore-postgresql:5432"
    ports:
      - "9083:9083"
  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:2.1.0
  presto-coordinator:
    image: shawnzhu/prestodb:0.181
    ports:
      - "8080:8080"
volumes:
  namenode:
  datanode:
